name: Fin3 Build and Publish

on:
  release:
    types:
      - created
  push:
    branches: [main, dev, protected]
  pull_request:
    branches: [main, dev]

jobs:

  docker_build:
    name: Build and Push to Docker Registry

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          if [[ "$VERSION" == "dev" || "$VERSION" == "main" ]]; then
              VERSION=latest
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV

          TAGS=$VERSION

          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          echo "This is test on Dev Branch"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run make devnet-start
        run: make docker-build-dev

      - name: Build and push service docker
        uses: docker/build-push-action@v2
        with:
          file: networks/dev/blockchain-dev/Dockerfile
          context: .
          push: true
          tags: fin3technologies/blockchain-dev:${{ steps.prep.outputs.tags }}
